enum MarketSector {
  CONSUMER_DISCRETIONARY,
  CONSUMER_STAPLES,
  COMMUNICATION_SERVICES,
  ENERGY,
  FINANCIALS,
  HEALTH_CARE,
  INDUSTRIALS,
  INFORMATION_TECHNOLOGY,
  MATERIALS,
  REAL_ESTATE,
  UTILITIES,
}
export default MarketSector;