enum MarketSector {
  MATERIALS,
  INDUSTRIALS,
  FINANCIALS,
  ENERGY,
  CONSUMER_DISCRETIONARY,
  INFORMATION_TECHNOLOGY,
  COMMUNICATION_SERVICES,
  REAL_ESTATE,
  HEALTH_CARE,
  CONSUMER_STAPLES,
  UTILITIES,
}
export default MarketSector;